name: Release Charts

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set up Chart Releaser
        uses: helm/chart-releaser-action@v1
        with:
          config: .cr.yaml
          token: ${{ secrets.CR_TOKEN }}  # Usando el secreto CR_TOKEN

      - name: Run Chart Releaser
        run: |
          cr index -o wissver-organization -r charts -c https://wissver-organization.github.io/charts
          cr upload -o wissver-organization -r charts --token ${{ secrets.CR_TOKEN }}  # Usando el token correcto

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs