name: Update Image

on:
  repository_dispatch:
    types:
      - update_image

permissions:
  contents: write
  
jobs:
  update_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Update the repository and tag in the file
        run: |
          # Actualizar el repository
          sed -i "s#repository: .*#repository: 621849652964.dkr.ecr.us-east-1.amazonaws.com/${{ github.event.client_payload.repository_name }}#" ${{ github.event.client_payload.file_path }}
          
          # Actualizar el tag
          sed -i "s#tag: .*#tag: \"${{ github.event.client_payload.tag }}\"#" ${{ github.event.client_payload.file_path }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.event.client_payload.file_path }}
          git commit -m "Update image tag in ${{ github.event.client_payload.file_path }}"
          git push origin ${{ github.ref }}
